### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by KMAyman** [data301-2021-summer2/group32-project#1]
Hello, 

My name is Ayman and I will be giving you some feedback on your project. 

Overall, the project is really high-quality work.

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1

Great work.

## Task 2

Great work.

## Task 3

Great work.

## Task 4

Great work.

**Comment by AashishChilwal** [comment]
Thank you for the great Feedback! 
I have made some changes in the EDA file, improved on my grammar, and added better statements for read me for each of the respective files
